### ISSUE TITLE
Monitoring per operation

### ISSUE THREAD

**Issue by hanny24** [twilio/guardrail#225]
This issue might be a more of a question rather than issue. I'm interested in a way how http4s generated code handles monitoring. Right now we are able to monitor things globally, ie. we can keep track of HTTP status codes returned by a server, but I'm not able to keep a track of status codes per endpoints/operationId.  Similar thing applies http4s server. How do you solve this? Or do you event solve it at all?

I have an idea how to modify current generator in order to suit our needs. Essentially it requires to be able to pass `String => Request[F] => F[Response[F]]` into every Client and Resource (server).

**Comment by blast-hardcheese** [comment]
This seems very close to `TraceBuilder`, https://github.com/twilio/guardrail/blob/320afebc2c26f800de7699bd009b314d4ed4c6be/modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sGenerator.scala#L53

Is what you're trying to do possible with that?

@cponomaryov Do you have any thoughts around this?

**Comment by hanny24** [comment]
`TraceBuilder` has two issues from my point of view:
- it works only for client side monitoring, not a server one
- it forces us to propagate `TraceBuilder` across whole application, which is something I would very much like to avoid.

**Comment by hanny24** [comment]
Let's try other way. How do you guys monitor http4s Responses (latency, success & failure rate)? From what I see it is only possible to monitor it globally, i.e not on single endpoint granularity.

I have an idea how to possibly modify/extend currently generated code, but I would like to do it only when it's absolutely needed. It might be a case I missed something.

**Comment by blast-hardcheese** [comment]
We currently use akka-http, so I don't know how this would work in http4s.

Our monitoring is effectively global, as you've described, by sanitizing the response URLs and emitting metrics from outside the application.

Looking again at `String => Request[F] => F[Response[F]]`, how would you implement this? This function, if passed in to the `Resource`, wouldn't have access to creating a `Response[F]`, would it?

Given that, wouldn't it be closer to `String => Request[F] => F[Response[F]] => F[Response[F]]` or `String => Request[F] => Response[F] => Response[F]`?

I could see the first being implemented as something like a response transformer, giving you complete access to the value coming from the response of whatever `Handler` method was called, where the second would be trying to inject into the router (at least the way akka-http does it, this could be different for http4s)

I agree with the direction you're going here, I didn't give enough consideration before when asking about `TraceBuilder`; it's necessary for us, due to needing to inject context headers into downstream client requests, but I can see how others may not need that.

**Comment by hanny24** [comment]
Sorry, my bad. Let me tree again:) Assuming `type Http4sHandler[F[_]] = Request[F] = F[Response[F]]` it should have really been `String => Http4sHandler[F] => Http4sHandler[F]`. So it essentially wraps generated handler with "Handler transformer". I just slightly modified your solution in a way that we even enable modification of incoming request. Does it make any sense?

**Comment by blast-hardcheese** [comment]
I think this makes sense. An implementation could be

```scala
operationId => mapper => { req =>
  val start = now()
  mapper(req).map { x =>
    val stop = now()
    emit(start, stop)
    x
  }
}
```
Is what you're thinking? Does http4s have a way to wrap an individual function in this way?

It still seems as though `String => Request[F] => Response[F] => Response[F]` is still more generally useful as least from akka-http, but maybe I'm just not seeing what you're getting at yet.

**Comment by cponomaryov** [comment]
Http4s has a notion of middleware: https://http4s.org/v0.20/middleware/
You can use them over generated code.
There is a metrics middleware in http4s: https://github.com/http4s/http4s/blob/master/server/src/main/scala/org/http4s/server/middleware/Metrics.scala
So you can use it or implement your own.

**Comment by hanny24** [comment]
Yes, http4s Middleware is exactly what I want. We just need to fix input parameters to `Request[F]` and output to `Response[F]`. I also like that it plays nicely with the rest of http4s framework.

**Comment by tomasherman** [comment]
I just gave it a couple of hours and failed. The issue is that the handler is never expressed in the shape of `Request[F] => F[Response[F]]` ... it looks like guardrail deconstructs the request into all it's parameters and then passes those to generated Handler interface ... unless im missing something

**Comment by blast-hardcheese** [comment]
Not on the individual message level, no. I presumed we'd need to decompose every single method into its own service, add metrics, then compose them back together.

How do others do this? `Request => F[Response]` seems like your entire service handler layer, which would be the output of `route(handler)

**Comment by tomasherman** [comment]
it turns out the solution can be quite simple ..

**Comment by blast-hardcheese** [comment]
@tomasherman This issue can be closed, now that #259 has been released?

**Comment by tomasherman** [comment]
Yep, we will probably want to add something similar for clients at some point (we are very pro-monitoring at avast :)) but for now we are good! Thank you

**Comment by blast-hardcheese** [comment]
Great! Feel free to reopen if necessary.
