### ISSUE TITLE
Encoding of optional fields

### ISSUE THREAD

**Issue by tomasherman** [twilio/guardrail#570]
Hey guys,

we ran into an issue. Our python using friends wrote some services that are not ok with missing optional fields being represented as `"somefield": null`, which is what guardrail/default circe encoder does. I was wondering - is there a good reason encoding fields this way? If not, would you be willing to change it for printer that drops null fields by default?

And if not, i guess we will need to somehow bend guardrail to accept optionally a custom printer.

What are your thoughts?

//cc @hanny24

**Comment by tomasherman** [comment]
one approach i was thinking about is adding optional setting field to guardrail which would disable the `import org.http4s.circe._` which would allow the user to provide it's own circe instances using custom imports - and it would not be a breaking change and also would not make the api for generated clients more complex

**Comment by blast-hardcheese** [comment]
This is related to the bigger issue of #315 -- I think if any work should be done in this direction, we should focus on fixing that instead of adding another vendor extension.

Vendor extensions for functionality like this is walking a very fine line, as the feature is already present in the specification language, we just don't support it correctly (similar to read or write-only values). I'm sympathetic towards your business needs, you may be able to work around this using something like

```scala
class StripNulls[A](val value: A)
object StripNulls {
  implicit def nullStrippingEncoder[A](implicit ev: Encoder.AsObject[A]): Encoder[StripNulls[A]] = ev.mapJsonObject(_.filter(!_._2.isNull)).contramap[StripNulls[A]](_.value)
}
```

```
scala> case class Foo(a: Option[Int], b: Option[String], c: Option[List[Boolean]])
defined class Foo

scala> implicit val encodeFoo: Encoder.AsObject[Foo] = Encoder.forProduct3("a", "b", "c")(o => (o.a, o.b, o.c))
encodeFoo: io.circe.Encoder.AsObject[Foo] = io.circe.ProductEncoders$$anon$3@51047a9b

scala> Foo(None, None, None).asJson
res0: io.circe.Json =
{
  "a" : null,
  "b" : null,
  "c" : null
}

scala> new StripNulls(Foo(None, None, None)).asJson
res1: io.circe.Json =
{

}
```

you'd just use `x-scala-type: hacks.StripNulls[Foo]`

**Comment by tomasherman** [comment]
closing as this is duplicate of #315
