### ISSUE TITLE
Error:No decoders available

### ISSUE THREAD

**Issue by runtologist** [twilio/guardrail#619]
Since upgrading from 0.56.0 to 0.57.*, one of my projects builds fails during `sbt guardrail` with the following error:

```
Error:No decoders available
[error] (Compile / guardrail) com.twilio.guardrail.sbt.CodegenFailedException
```

No additional output is given and `last guardrail` does not provide any additonal information. The only difference in the generated code seems to be the addition of `Base64String` in `Implicits.scala`, which is not used in the project. That additiona works in all my other projects anyway.

I'm not aware of any particular guardrail features in this openapi spec, which I do not use anywhere else. 

I'd be very happy about any hint about where to look to debug this further. The project is a closed source product. For that reason I'm not attaching the openapi spec, but I'll happily share it for debugging purposes.

**Comment by runtologist** [comment]
It looks like the code generation is already done or almost done at the time of the failure. When I  create a build definition for bloop manually, and use that to work around the failing sbt task, the generated code compiles and runs just fine.

**Comment by blast-hardcheese** [comment]
@runtologist Ah, it looks like the associated [`warning`](https://github.com/twilio/guardrail/blob/8e8b3d6/modules/codegen/src/main/scala/com/twilio/guardrail/generators/Scala/AkkaHttpHelper.scala#L20) isn't getting emitted, as I've temporarily disabled the logger due to performance issues.

The emitted error additionally doesn't include the history of which node in the OpenAPI specification is causing the problem, which further worsens things.

I can't actually see how this would have changed with the 0.56.x -> 0.57.x change, but to confirm that my assumption is correct, please verify that all routes either don't specify a `consumes`, or that `consumes` contains either `application/json` or `text/plain`

**Comment by runtologist** [comment]
I use OAS 3.0. All `content` types are àpplication/json`.

**Comment by blast-hardcheese** [comment]
@runtologist If you wouldn't mind sharing the spec in private, I'm https://twitter.com/blast_hardchese . I can run it locally with debug turned on

**Comment by blast-hardcheese** [comment]
So, to circle back, this turned out to be because of an currently unsupported content type, `application/vnd.yaml`. It may be able to be supported better with techniques introduced by #571, though the accepted workaround was to just change to `text/plain` for the time being.

**Comment by runtologist** [comment]
Thanks again for the quick help!
