### ISSUE TITLE
Missing AddArg.addArgVector?

### ISSUE THREAD

**Issue by francescopellegrini** [twilio/guardrail#622]
Hi,
[v0.55.0](https://github.com/twilio/guardrail/blob/master/MIGRATING.md#0550-may-contain-breaking-changes-for-scala-clients-and-servers) changed the Scala type for OpenAPI's `type: array` from `IndexedSeq` to `Vector`, but I noticed [AddArg](https://github.com/twilio/guardrail/blob/master/modules/codegen/src/main/scala/com/twilio/guardrail/generators/ScalaGenerator.scala#L209) doesn't provide an implicit `addArgVector`: is this a bug or the intended behavior to have clients migrate to `Iterable`?

Note that query params defined as array of strings are generated as `Iterable[String]`, not `Vector[String]`!

Thank you so much for the amazing library!

**Comment by blast-hardcheese** [comment]
Definitely a bug, sorry to hear this slipped through the tests!

As a stop gap you can:
- define your own instance of `AddArg[Vector[A]]` based on the implementation of the IndexedSeq or Iterator implicits, then import the instances using the `ScalaClient(..., imports=...)` parameter in your build.sbt
- Use `x-scala-array-type: IndexedSeq` to use the previous behavior ([migration notes for 0.55.0](https://github.com/twilio/guardrail/blob/master/MIGRATING.md))

Either way, thanks for reporting it! If you've got the time to open a PR with the fix and a regression test (should be as simple as adding a failing specification to the list in `build.sbt`) that would be very much appreciated, otherwise I'll try to do it beginning of next week.

**Comment by blast-hardcheese** [comment]
So, coming back to this...

I tried to replicate the issue with the following spec:

```yaml
openapi: 3.0.2
servers:
  - url: "http://localhost:1234"
paths:
  /foo:
    post:
      operationId: doFoo
      responses:
        '204':
          description: No response
      parameters:
        - name: vector
          in: query
          required: false
          schema:
            type: array
            items:
              type: integer
              format: int64
```

... but I got the following method generated:
```scala
def doFoo(vector: Option[Iterable[String]] = None, ...): EitherT[Future, Either[Throwable, HttpResponse], DoFooResponse]
```

... which is compatible with `Vector`, as `Vector[A] <:< Iterable[A]`:
```
scala> Vector.empty[Long]: Iterable[Long]
res0: Iterable[Long] = Vector()
```

How can I reproduce the issue you are seeing?

**Comment by francescopellegrini** [comment]
Hi @blast-hardcheese,
I used the following descriptor, which generated Client doesn't compile: `could not find implicit value for parameter ev: swagger.Implicits.AddArg[Option[Vector[String]]]`

```yaml
openapi: 3.0.2
servers:
  - url: "http://localhost:1234"
paths:
  /foo:
    post:
      operationId: doFoo
      responses:
        '204':
          description: No response
      parameters:
        - name: vector
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/MyVector'
components:
  schemas:
    MyVector:
      type: array
      items:
        type: string
```

**Comment by blast-hardcheese** [comment]
Oh! It looks like the `type: array` is not being dereferenced properly through the `$ref` -- if you inline that definition as a workaround, there should be a usable client generated.

Thank you for the spec, I'll see what I can do 😊

**Comment by blast-hardcheese** [comment]
@francescopellegrini OK! Just pushed up 0.57.4. It may take some time to sync with maven central, but I believe this will resolve the issue you were facing.

Your initial PR actually turned out to be exactly on the right track, though actually pushing it over the line required a little more in-depth knowledge than I anticipated.

I thought it was going to be a 3-10 line change, which is why I put the "good first issue" tag on.
I really misjudged that, I apologize.

**Comment by francescopellegrini** [comment]
Hi @blast-hardcheese, thank you very much for the quick fix and the kind response. No need to apologize, cheers!
