### ISSUE TITLE
Contribution question - publishLocal

### ISSUE THREAD

**Issue by maciejbak85** [twilio/guardrail#737]
Hi,

I am trying to fix one problem, when I do publishLocal and try to use library ( without changes still )  I have then errors like:

 ```
error: not found: value guardrailTasks
guardrailTasks in Compile := List(
^
/home/baku/Dev/workspace/job/os/http4s-guardrail-example/build.sbt:37: error: not found: value ScalaServer
  ScalaServer(
  ^
/home/baku/Dev/workspace/job/os/http4s-guardrail-example/build.sbt:38: error: not found: value specPath
    specPath = (Compile / resourceDirectory).value / "api.yaml",
    ^
/home/baku/Dev/workspace/job/os/http4s-guardrail-example/build.sbt:39: error: not found: value pkg
    pkg = "com.example.http4sguardrailexample",
    ^
/home/baku/Dev/workspace/job/os/http4s-guardrail-example/build.sbt:40: error: not found: value framework
    framework = "http4s",
    ^
/home/baku/Dev/workspace/job/os/http4s-guardrail-example/build.sbt:41: error: not found: value tracing
    tracing = false
    ^
```

any of you occured similar issue ?

**Comment by blast-hardcheese** [comment]
Hello @maciejbak85! Due to the fact that the sbt plugin is in a separate project, https://github.com/twilio/sbt-guardrail, you'll likely need to build and `publishLocal` that project as well if you want the full chain to function as expected.

When developing changes, I typically use `cli` on the SBT console from inside guardrail to run my configuration,
```
sbt> ~cli scala --server --specPath ~/example/api.yaml --framework http4s --packageName com.example.http4sguardrailexample --outputPath ~/example/src/main/scala/generated
```
for example.

This has the benefit of having a quick iteration cycle from both sides, if you make modifications by hand inside `~/example/` you can see the effect immediately, and as you migrate those changes into the guardrail generator you can compare the generated code with what you expect by verifying the `git diff` as you go.

**Comment by blast-hardcheese** [comment]
Closing this out, but feel free to comment if you still feel as though there is an opportunity to improve this workflow.
