### ISSUE TITLE
Http4s Client POST doesn't use the correct with body

### ISSUE THREAD

**Issue by calvinbrown085** [twilio/guardrail#85]
When generating a client with a function I recieve

```
def getConfiguration(getConfigurationRequest: GetConfigurationRequest, headers: List[Header] = List.empty): F[GetConfigurationResponse] = {
    val allHeaders = headers ++ List[Option[Header]]().flatten
    httpClient.expect[GetConfigurationResponse](Request[F](method = Method.POST, uri = Uri.unsafeFromString(host + basePath + "/get-configuration"), headers = Headers(allHeaders)).withBody("getConfigurationRequest"))
  }

```

We probably want something like `.withBody(getConfigurationRequest.asJson))` instead, assuming you are using JSON

**Comment by blast-hardcheese** [comment]
Interesting; I need to spend more time with http4s and get real end-to-end roundtrip test working, bringing http4s support up to parity with the akka-http support. Thanks for reporting this!

**Comment by blast-hardcheese** [comment]
That looks like a great place to start.

I believe the actual culprit is a few steps up in the process, this [toLit](https://github.com/twilio/guardrail/blob/master/modules/codegen/src/main/scala/com/twilio/guardrail/generators/Http4sClientGenerator.scala#L169) would produce the `Lit.String(...)` you're seeing (comparing with the [akka-http equivalent](https://github.com/twilio/guardrail/blob/master/modules/codegen/src/main/scala/com/twilio/guardrail/generators/AkkaHttpClientGenerator.scala#L177-L178) may be instructive)

(I added `text/plain` support to akka-http recently, though the matching refactor isn't present in http4s)

**Comment by blast-hardcheese** [comment]
This seems to have been resolved in release [v0.39.0](https://github.com/twilio/guardrail/releases/tag/v0.39.0) (19d215f6306f291be9ce440ed2c964a663c2ba4a)

**Comment by calvinbrown085** [comment]
Awesome, thanks @blast-hardcheese !

**Comment by blast-hardcheese** [comment]
You're welcome!
